### ISSUE TITLE
Нарисовать диаграмму объектов

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#10]

**Comment by dronnikovigor** [comment]
![ДиаграммаОбъектов](https://user-images.githubusercontent.com/4175117/58379659-51ce7500-7faf-11e9-887e-a9273a4171ab.jpg)
[ДиаграммаОбъектов.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220150/default.zip)

**Comment by dronnikovigor** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/4175117/58965631-93360000-87b9-11e9-95b0-95e8a7ba1ffc.png)

[Untitled Diagram.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3257681/Untitled.Diagram.zip)
