### ISSUE TITLE
Нарисовать диаграмму последовательностей

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#11]

**Comment by dronnikovigor** [comment]
![ДиаграммаПослед](https://user-images.githubusercontent.com/4175117/58379991-af64c080-7fb3-11e9-902a-de32a8385c64.jpg)
[ДиаграммаПослед.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220165/default.zip)
