### ISSUE TITLE
Нарисовать диаграмму развертывания

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#12]

**Comment by dronnikovigor** [comment]
![ДиаграммаРазв](https://user-images.githubusercontent.com/4175117/58379458-3b72ea00-7fac-11e9-9ed6-fc5f8f990c25.jpg)
[ДиаграммаРазв.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220133/default.zip)
