### ISSUE TITLE
Нарисовать диаграмму состояний

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#13]

**Comment by dronnikovigor** [comment]
![ДиаграммаСост](https://user-images.githubusercontent.com/4175117/58379380-32354d80-7fab-11e9-8d85-ce57c6dcbabb.jpg)

[ДиаграммаСост.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220125/default.zip)
