### ISSUE TITLE
Подготовить схему навигации

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#16]

**Comment by JuliaPol** [comment]
![nav](https://user-images.githubusercontent.com/15696755/58383066-c5d24280-7fda-11e9-8fcb-62158221c77f.jpg)

**Comment by JuliaPol** [comment]
[Схема навигации.docx](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220399/default.docx)
