### ISSUE TITLE
Подготовить документ архитектуры ПО (+диаграмма классов)

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#17]
+ в этот же документ будет включено https://github.com/dronnikovigor/PostDeliveryLogistics/issues/9

**Comment by JuliaPol** [comment]
![Main](https://user-images.githubusercontent.com/15696755/58593381-6c387500-8273-11e9-86f2-b76b49e27278.jpg)
