### ISSUE TITLE
Создать диаграмму Ганта

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#5]

**Comment by JuliaPol** [comment]
![image](https://user-images.githubusercontent.com/15696755/57986573-29122100-7a7f-11e9-8a57-b9afad8f317b.png)
![image](https://user-images.githubusercontent.com/15696755/57986583-48a94980-7a7f-11e9-9a84-f31b3494560a.png)
![image](https://user-images.githubusercontent.com/15696755/57986587-5068ee00-7a7f-11e9-89ad-6d0aa14a9b2b.png)
![image](https://user-images.githubusercontent.com/15696755/57986607-a5a4ff80-7a7f-11e9-9102-60e37b42d0a0.png)
