### ISSUE TITLE
Нарисовать диаграмму коммуникации

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#8]

**Comment by dronnikovigor** [comment]
![ДиаграммаКомм](https://user-images.githubusercontent.com/4175117/58380185-d7095800-7fb6-11e9-8f84-1647d12f7f5d.jpg)
[ДиаграммаКомм.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220184/default.zip)
