### ISSUE TITLE
Нарисовать диаграмму компонентов

### ISSUE THREAD

**Issue by Tanya-Gordeyeva** [dronnikovigor/PostDeliveryLogistics#9]

**Comment by dronnikovigor** [comment]
![ДиаграммаКомп](https://user-images.githubusercontent.com/4175117/58380060-dcfe3980-7fb4-11e9-85a6-a62893ec496d.jpg)
[ДиаграммаКомп.zip](https://github.com/dronnikovigor/PostDeliveryLogistics/files/3220174/default.zip)

**Comment by dronnikovigor** [comment]
![image](https://user-images.githubusercontent.com/4175117/58960577-236f4780-87b0-11e9-916c-a280ad8234f3.png)
